### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by lidudutju** [acetous/gradle-require-dependency-compliance#19]
gradle version: 4.4

```groovy
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/internal/artifacts/DefaultProjectComponentIdentifier
        at de.acetous.dependencycompliance.DependencyTask.lambda$resolveDependencies$2(DependencyTask.java:84)
        at de.acetous.dependencycompliance.DependencyTask.resolveDependencies(DependencyTask.java:90)
        at de.acetous.dependencycompliance.DependencyListTask.listDependencies(DependencyListTask.java:14)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 31 more


```

**Comment by lidudutju** [comment]
Tried to update gradle version to 4.8.1. Problem solved!

**Comment by acetous** [comment]
Hi @lidudutju, the plugin is only tested with Gradle 4.8.1. I'm currently looking into testing things with different versions of Gradle. Until that is done I cannot guarantee compatiblity with other versions.

**Comment by lidudutju** [comment]
@acetous Got it. Thanks for the reply.

**Comment by acetous** [comment]
The plugin is now tested with multiple Gradle versions, see #20. Gradle 4.8 or newer work fine.
